language: ruby
cache: bundler

matrix:
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.5
      os: osx
      env:
        # TODO: 0.8 is enough on Linux, but 2 seems needed for Travis/OSX
        - LISTEN_TESTS_DEFAULT_LAG=2
    - rvm: jruby
      env:
        - LISTEN_TESTS_DEFAULT_LAG=10
        - TEST_LISTEN_ADAPTER_MODES=native
        - LISTEN_GEM_DEBUGGING=2
    - rvm: truffleruby
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: rbx-3
  allow_failures:
    - rvm: truffleruby
    - rvm: jruby
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
  fast_finish: true
